### ISSUE TITLE
NYT: Book Review archive support + more filtering

### ISSUE THREAD

**Issue by owcz** [zotero/translators#1372]
Separating other issues mentioned in #1362 to another PR

Still finding a few pages of NYT archives that need better handling & wanted to collect them publicly:

* [x] Handle author of http://www.nytimes.com/1985/10/20/books/in-the-spirit-of-68.html
    - [ ] (works when logged out but hangs when logged in) - need to test now that PDF saving was removed
* [ ] Handle book review archives, such as http://www.nytimes.com/books/98/12/06/specials/holmes-footsteps.html
* [x] Date and site name in blogs ([example](https://lens.blogs.nytimes.com/2012/09/17/picturing-everyday-life-in-africa/), [another](https://green.blogs.nytimes.com/2010/10/15/the-battle-of-newtown-creek/))
* [ ] Times Machine ([this](http://query.nytimes.com/gst/abstract.html?res=9B07EFD81F3DEE3BBC4951DFB467838C679EDE&legacy=true) supports PDF download, but [its corresponding TM page](https://timesmachine.nytimes.com/timesmachine/1967/12/21/88497827.html?pageNumber=34) is unhandled & defaults to EM)
* [x] Correct duplicate semicolon titles, such as ["Paris Was Burning; Paris Was Burning"](http://query.nytimes.com/gst/abstract.html?res=9501E6DD1430E43BBC4E52DFB667838D679EDE), sometimes presented with one side of the semicolon identical but all caps
    * letting this one go as something for the Times to manually process on their end, but for more examples see, for example, [their sitelist](http://spiderbites.nytimes.com/1966/articles_1966_11_00000.html) from any given historical month and headlines such as `U.S. Pilot Describes Fiery Landing; U.S. PILOT TELLS OF FIERY LANDING` or `Lortogs Seeking to Make Comeback; LORTOGS SEEKING TO REVERSE LOSS` (the article subtitle or the header used after the break is included as the metadata title even it's nearly or fully identical to the original header)
    * This said, I'd prefer the translator to strike the subheader after the semicolon if registered as identical to the original header, as that scenario is much more likely as a transcription error than as a deliberate style choice
* [x] Handle multiple authors ([example](https://www.nytimes.com/interactive/2017/11/10/us/men-accused-sexual-misconduct-weinstein.html))
* [x] Wrong author in interactive feature ([example](https://www.nytimes.com/interactive/2017/12/13/magazine/the-reckoning-women-and-power-in-the-workplace.html?_r=0))
    * letting this one go as the long multi-author byline is entered as "description" rather than marked as "authors" in the metadata, though this would be annoying for anyone citing the full article
* [x] Support for new NYT search
* [x] Pull author field in feature articles ([example](https://www.nytimes.com/2018/04/07/style/the-juul-is-too-cool.html))
* [ ] author missing from [this obit](https://www.nytimes.com/2018/09/26/obituaries/voltairine-de-cleyre-overlooked.html)
* [ ] pulls URL twice on [this magazine piece](https://www.nytimes.com/interactive/2018/10/24/magazine/candy-world-favorite.html)

**Comment by owcz** [comment]
Can't edit my above comment. A few more:
* Support for new NYT search
* Pull author field in feature articles ([example](https://www.nytimes.com/2018/04/07/style/the-juul-is-too-cool.html))

**Comment by zuphilip** [comment]
With the merge of #1623 some of these points are fixed. I didn't look into book reviews and I don't have access to the PDFs.

@owcz Can you update what is still open?

**Comment by owcz** [comment]
@zuphilip updated checkboxes in the OP

- Search multiple pulls `<p class="Item-section--1T6pp">Section Name</p>` too instead of just the page title

- Still doesn't handle the authors in the interactive feature but not sure if that's just an edge case

- Issue with title duplicated after semicolon <https://www.nytimes.com/1966/10/16/archives/paris-was-burning-paris-was-burning.html> still unhandled, but perhaps that's on the Times to fix. I used to hit these examples all the time and I couldn't find another example in my library, so perhaps they're fixed already? 

- Biggest issue: When logged in, translator now hangs on pages like
https://www.nytimes.com/1985/10/20/books/in-the-spirit-of-68.html
https://www.nytimes.com/1967/12/21/archives/book-editors-finish-summerof-1968-that-is.html
(That same page used to be
http://query.nytimes.com/gst/abstract.html?res=9B07EFD81F3DEE3BBC4951DFB467838C679EDE&legacy=true)
So perhaps the PDF capture code just needs to move to accommodate the URL change?

- **Blogs**
Are https://lens.blogs.nytimes.com/2012/09/17/picturing-everyday-life-in-africa/ and https://green.blogs.nytimes.com/2010/10/15/the-battle-of-newtown-creek/
better titled "Lens Blog" and "Green Blog" or "New York Times Lens Blog" etc. It's not like "Lens Blog" is how the blog is known

**Comment by zuphilip** [comment]
> Search multiple pulls `<p class="Item-section--1T6pp">Section Name</p>` too instead of just the page title

I don't understand this. Do you have an example url?

> Still doesn't handle the authors in the interactive feature but not sure if that's just an edge case

Well, the authors are not marked anyhow in [that website](http://www.nytimes.com/books/98/12/06/specials/holmes-footsteps.html), but they are part of the description which is saved in Zotero as the abstract. Not much more we can do here...

> Issue with title duplicated after semicolon...

That should be an issue which NYTimes should fix on their side.

BTW the book review pages don't have any structured information to start with and therefore not much we can do about them.

> Biggest issue: When logged in, translator now hangs on pages like ...

I am not a subscriber and thus cannot log in. Someone with a log in has to work on this....

> Blogs ...

It is possible to replace these two blog names with a more meaningful name in the Zotero translator.

**Comment by owcz** [comment]
![image](https://user-images.githubusercontent.com/778011/39091069-d59084bc-45ba-11e8-882e-9bc0ac342332.png)
(Multi pop-up displays section headers, not just titles)

Will have to take a look at the other parts in the future

Re: archive PDF, I'm having trouble capturing the redirection page (as done in #1361) so that the translator uses the direct PDF rather than the authentication page (which forwards). Might want to comment out out PDF download function code until that feature is cleared

**Comment by zuphilip** [comment]
Okay, I pushed another PR to improve multiples and deactivate PDFs completely until someone fixes it #1632.

**Comment by owcz** [comment]
Any reason why this translator uses `dateModified` instead of `datePublished`? I just realized that many of my citations are referring to dates that never show in the article text...

```html
<meta data-rh="true" property="article:published" itemprop="datePublished" content="2017-05-22T04:01:31.000Z">
<meta data-rh="true" property="article:modified" itemprop="dateModified" content="2018-04-04T22:02:16.090Z">
```
https://www.nytimes.com/2017/05/22/world/europe/greece-athens-anarchy-austerity.html

**Comment by zuphilip** [comment]
We can fix the dates. The publication date should be preferred over the modified date. I will make a PR for that... 

> Also the translator's snapshot component hasn't been triggering recently

The snapshot was disabled some days ago because it didn't work properly, cf. https://github.com/zotero/translators/issues/1807.

**Comment by zuphilip** [comment]
I fixed the date and some other small things. Thus, I close this 2-year-old issue now and suggest, that you open a new one if there is anything left.
