### ISSUE TITLE
No pdf from ScienceDirect

### ISSUE THREAD

**Issue by slmeyer** [zotero/translators#2739]
Both without institution recirect with open access and with redirect never any pdf from Clinical Psychology Review.
Tried to update and reset translators without any effect.

**Comment by dstillman** [comment]
@slmeyer: Are you still seeing this? If so, can you provide a <a href="https://www.zotero.org/support/debug_output#debug_output_logging">Debug ID</a> from Zotero for a save attempt that fails after reloading the page?

**Comment by slmeyer** [comment]
Now for open access articles the problem is solved, but remains for others accessed through institution proxy
Debug id: D433737580

**Comment by dstillman** [comment]
It's not fixed for anything — it's just intermittent, based on selective anti-bot behavior from Elsevier. We're working on a fix, but it will require fairly significant changes within the Zotero app to support this (and is something that's not necessary for any other site that I'm aware of).
